### ISSUE TITLE
Minimal example for testing node functionality

### ISSUE THREAD

**Issue by fmessmer** [koellsch/obstacle_distance#2]
I'm trying to get this node to run, but I'm missing a minimal example or some HowTo instructions.
How can I test the functionality of the `obstacle_distance` node stand-alone, i.e. without atf?

**Comment by fmessmer** [comment]
fixed in #3 

Terminal 1: `roslaunch cob_bringup_sim robot.launch robot:=cob4-2`
Terminal 2: `rosrun obstacle_distance obstacle_distance_node`
Terminal 3: `rosrun obstacle_distance test_obstacle_publisher.py`
Terminal 3: `rosrun obstacle_distance test_service_client.py`

**Comment by fmessmer** [comment]
Does the node only calculate distance to the collision_objects known to the PlanningScene or can it also compute distances between self-collision_links, e.g. `arm_left_7_link` vs. `torso_3_link`?
How would I do that?

**Comment by koellsch** [comment]
Not at the moment. I know that the FCL and MoveIt! are capable of doing so but this node isn't yet.
I tried replacing the collision_object with a second robot link but the distances were calculated without regarding the geometry of the robot. I am trying to add this feature when I got time.

**Comment by fmessmer** [comment]
Thanks for the reply...

Also, I wanted to ask about license and maintainership of this package.
Would it be ok for you, if I try to use your code in order to solve https://github.com/ipa320/cob_control/issues/77?
I.e. I'm currently thinking about "merging"/"combining" the functionality of three packages:
- https://github.com/ipa320/cob_control/tree/indigo_dev/cob_obstacle_distance
- https://github.com/ipa320/cob_manipulation/tree/indigo_dev/cob_collision_monitor
- https://github.com/koellsch/obstacle_distance

into one that lives somewhere within the ipa320 organization (again) - most likely `cob_control`, `cob_manipulation` or `cob_driver`....

I would try to keep the interfaces as they are, i.e. allow the current `cob_obstacle_distance` interfaces being used as well as the ones being used within `atf`....

**Comment by koellsch** [comment]
No problem. Feel free to use it.
If you find a way to compute distances for self-collision before I do, feel free to message me or create a pull request, so that I can implement this feature into my node.

**Comment by fmessmer** [comment]
@koellsch 
FYI,  development is continued on branch https://github.com/ipa-fxm/obstacle_distance/tree/feature_registration_service_and_continuous_publisher together with @ipa-fxm-cm

So far, we added: 
- computation/transformation of nearest points of the respective CollisionObjects
- visualization of the PlanningScene
- visualization of the Distances (using visualization_msgs::Marker "arrows")
- read SRDF from `cob_moveit_config`

To be continued...
- DistanceComputation for self-collision links has been added
- PlanningSceneMonitor also considers SensorInput within an octomap (not yet used within DistanceComputation)

**Comment by fmessmer** [comment]
As you allowed us to use your code within `ipa320` I prepared a PR to `cob_manipulation` bringing this package (+ my extension) back into `ipa320` ==> see https://github.com/ipa320/cob_manipulation/pull/64

**Comment by fmessmer** [comment]
#3 has been merged!
https://github.com/ipa320/cob_manipulation/pull/64 has been merged, too....I'll continue development in `cob_manipulation`....
